apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webhook
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-webhook
  template:
    metadata:
      labels:
        app: my-webhook
    spec:
      containers:
      - name: webhook
        image: my-webhook-image:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: WATCH_NAMESPACE
          value: "my-namespace"
        - name: TARGET_LABEL
          value: "my-label"
        - name: CPU_LIMIT
          value: "1000m"
        - name: CPU_REQUEST
          value: "500m"
        - name: MEMORY_LIMIT
          value: "1Gi"
        - name: MEMORY_REQUEST
          value: "500Mi"
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: my-webhook
  namespace: my-namespace
spec:
  ports:
  - port: 443
    targetPort: 8080
  selector:
    app: my-webhook