apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: webhook-server
webhooks:
  - name: webhook.example.com
    matchPolicy: Equivalent
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions: ["v1"]
    clientConfig:
      caBundle: <base64-encoded server.crt content>
      url: "https://<your-webhook-domain-or-ip>:8443/mutate"

#使用以下命令将生成的 `webhook-crt.pem` 证书的内容注入到 `caBundle` 字段中：

#```bash
#CABUNDLE=$(cat webhook-crt.pem | base64 | tr -d '\n')
#envsubst < validating-webhook-configuration.yaml | kubectl apply -f -
