apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
 name: my-webhook-configuration
webhooks:

name: my-webhook.my-namespace.svc
sideEffects: None
admissionReviewVersions: ["v1"]
rules:
apiGroups: [""]
apiVersions: ["v1"]
operations: ["CREATE", "UPDATE"]
resources: ["pods"]
scope: "Namespaced"
clientConfig:
service:
namespace: my-namespace
name: my-webhook
path: "/mutate"
caBundle: ${CABUNDLE}


#使用以下命令将生成的 `webhook-crt.pem` 证书的内容注入到 `caBundle` 字段中：

#```bash
#CABUNDLE=$(cat webhook-crt.pem | base64 | tr -d '\n')
#envsubst < validating-webhook-configuration.yaml | kubectl apply -f -
